version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hospital_management_app
    container_name: hospital_management_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/app.ini
    networks:
      - hospital_management_network

  webserver:
    image: nginx:alpine
    container_name: hospital_management_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - hospital_management_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: hospital_management_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - hospital_management_network

  node:
    image: node:22
    container_name: hospital_management_node
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "5173:5173" # Vite dev server port
    networks:
      - hospital_management_network
    command: sh -c "npm install && npm run dev"
    depends_on:
      - app

volumes:
  dbdata:
    driver: local

networks:
  hospital_management_network:
    driver: bridge